### ISSUE TITLE
cosign-generate-keypair broken for use with images-website

### ISSUE THREAD

**Issue by RoyalOughtness** [ublue-os/images-website#18]
the 

podman run -it ghcr.io/ublue-os/cosign-generate-keypair

is currently broken for use with startingpoint webui. It results in an error saying that

-----BEGIN ENCRYPTED SIGSTORE PRIVATE KEY-----

should be

-----BEGIN ENCRYPTED COSIGN PRIVATE KEY-----
but it shouldn't, since the former works in the build and the latter fails

**Comment by xynydev** [comment]
Ok, so this change in the key header happened as part of the update I did on the cosign container earlier since I thought that was the route cause of a problem, which it was actually not. 

>  since the former works in the build and the latter fails

I just tried and both worked in the GHA builds. To be clear, I think these are different versions of the key format and you have to regenerate the keys if you want to use the newer _SIGSTORE_ header. 

I'll just keep the container like it is, and add support for keys with the  _SIGSTORE_ header.

**Comment by xynydev** [comment]
This should fix the problem [624e5dc](https://github.com/ublue-os/images-website/commit/624e5dc3d7c91347cafd96dd3ff383982fea46e2).
